plugins {
    id 'java'
}

group = 'vn.edu.ueh.bit'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.hadoop:hadoop-common:3.4.3")
    implementation("org.apache.hadoop:hadoop-hdfs:3.4.3")
    implementation("org.apache.hadoop:hadoop-mapreduce-client-core:3.4.3")
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}